// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/macros/s/AKfycbwQdpgXGwnMQHuQaXcE9NQALIMOW2stH7r-8uKkviAHf0kI5ewLul-Mxq4IWZPEv7OfUA/exec";
